// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelArchive() {
  return window['go']['main']['App']['CancelArchive']();
}

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function ClassifierStatus() {
  return window['go']['main']['App']['ClassifierStatus']();
}

export function ConfirmClose() {
  return window['go']['main']['App']['ConfirmClose']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetDestinationInfo(arg1) {
  return window['go']['main']['App']['GetDestinationInfo'](arg1);
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListDrives() {
  return window['go']['main']['App']['ListDrives']();
}

export function LogFrontendError(arg1) {
  return window['go']['main']['App']['LogFrontendError'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PauseArchive() {
  return window['go']['main']['App']['PauseArchive']();
}

export function PickFolder(arg1) {
  return window['go']['main']['App']['PickFolder'](arg1);
}

export function Reindex(arg1) {
  return window['go']['main']['App']['Reindex'](arg1);
}

export function ResumeArchive() {
  return window['go']['main']['App']['ResumeArchive']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartArchive(arg1) {
  return window['go']['main']['App']['StartArchive'](arg1);
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}

export function SystemTheme() {
  return window['go']['main']['App']['SystemTheme']();
}
