// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {classify} from '../models';
import {main} from '../models';
import {config} from '../models';
import {drives} from '../models';

export function CancelArchive():Promise<void>;

export function CancelScan():Promise<void>;

export function ClassifierStatus():Promise<classify.Status>;

export function ConfirmClose():Promise<void>;

export function GetDestinationInfo(arg1:string):Promise<main.DestinationInfo>;

export function GetSettings():Promise<config.Settings>;

export function ListDrives():Promise<Array<drives.Drive>>;

export function LogFrontendError(arg1:string):Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function PauseArchive():Promise<void>;

export function PickFolder(arg1:string):Promise<string>;

export function Reindex(arg1:string):Promise<void>;

export function ResumeArchive():Promise<void>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function StartArchive(arg1:main.ArchiveRequest):Promise<void>;

export function StartScan(arg1:Array<string>):Promise<void>;
